In [2]:
conda list ipython

# packages in environment at C:\Users\Win\Miniconda3\envs\naya:
#
# Name                    Version                   Build  Channel
ipython                   7.16.1           py37h5ca1d4c_0  
ipython_genutils          0.2.0                    py37_0  

Note: you may need to restart the kernel to use updated packages.


In [3]:
!conda list python

# packages in environment at C:\Users\Win\Miniconda3\envs\naya:
#
# Name                    Version                   Build  Channel
ipython                   7.16.1           py37h5ca1d4c_0  
ipython_genutils          0.2.0                    py37_0  
python                    3.7.7                h81c818b_4  
python-dateutil           2.8.1                      py_0  
python-jsonrpc-server     0.3.4                      py_0  
python-language-server    0.31.10                  py37_0  


#### Randomly Initialized Tensor

In [4]:
from __future__ import print_function
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.0904, 0.2907, 0.6003],
        [0.5822, 0.7333, 0.7658],
        [0.6141, 0.6741, 0.9436],
        [0.4118, 0.0745, 0.3731],
        [0.2459, 0.7998, 0.9322]])


#### To check GPU & CUDA

In [5]:
import torch
torch.cuda.is_available()

False

In [6]:
import numpy as np

In [7]:
from __future__ import print_function
import torch

An uninitialized matrix is declared, but does not contain definite known values before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.

In [8]:
x = torch.empty(5,3)
x

tensor([[9.3674e-39, 9.9184e-39, 8.7245e-39],
        [9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0378e-38],
        [9.6429e-39, 9.2755e-39, 9.7346e-39]])

Construct a randomly initialized matrix:

In [9]:
y = torch.rand(5,5)
y

tensor([[0.5673, 0.5360, 0.8945, 0.0485, 0.0766],
        [0.9318, 0.9904, 0.4229, 0.1721, 0.0426],
        [0.4057, 0.2996, 0.9124, 0.7632, 0.0910],
        [0.7429, 0.4530, 0.5672, 0.5330, 0.7592],
        [0.3482, 0.8346, 0.1272, 0.3490, 0.9012]])

In [10]:
y.dtype

torch.float32

Construct a matrix filled zeros and of dtype long:

In [11]:
z = torch.zeros((5,3), dtype = torch.long)
z, z.dtype

(tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
 torch.int64)

#### Construct a tensor directly from data:

In [12]:
x = torch.tensor([5.5,3,5,6])
x

tensor([5.5000, 3.0000, 5.0000, 6.0000])

In [13]:
tup_tensor = torch.tensor((2,3,4,1))
tup_tensor,tup_tensor.dtype

(tensor([2, 3, 4, 1]), torch.int64)

#### create a tensor based on an existing tensor

In [14]:
## new_* methods take in sizes
x = x.new_ones(5,3, dtype = torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [15]:
# overrride dtype
x = torch.randn_like(x, dtype = torch.float)

In [16]:
print(z.size())

torch.Size([5, 3])


In [17]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[-0.3107, -1.1758, -0.4191],
        [-0.6334,  0.9185, -0.6021],
        [ 1.3383, -0.8099,  0.5962],
        [-0.6927,  0.0041,  0.9993],
        [-0.5053,  2.4848, -1.1271]])


### Operations

In [18]:
y = torch.rand(5,3)
y,x+y

(tensor([[0.8739, 0.4182, 0.6697],
         [0.0854, 0.0284, 0.5977],
         [0.8708, 0.4873, 0.0058],
         [0.6327, 0.9869, 0.3625],
         [0.1817, 0.7000, 0.6424]]),
 tensor([[ 0.5632, -0.7577,  0.2506],
         [-0.5480,  0.9469, -0.0045],
         [ 2.2092, -0.3226,  0.6020],
         [-0.0600,  0.9910,  1.3617],
         [-0.3236,  3.1849, -0.4847]]))

In [19]:
print(torch.add(x,y))

tensor([[ 0.5632, -0.7577,  0.2506],
        [-0.5480,  0.9469, -0.0045],
        [ 2.2092, -0.3226,  0.6020],
        [-0.0600,  0.9910,  1.3617],
        [-0.3236,  3.1849, -0.4847]])


In [20]:
a = torch.add(x,y)
print(torch.add(x,y,out=  a))

tensor([[ 0.5632, -0.7577,  0.2506],
        [-0.5480,  0.9469, -0.0045],
        [ 2.2092, -0.3226,  0.6020],
        [-0.0600,  0.9910,  1.3617],
        [-0.3236,  3.1849, -0.4847]])


In [21]:
# inplace addition
x.add(y)

tensor([[ 0.5632, -0.7577,  0.2506],
        [-0.5480,  0.9469, -0.0045],
        [ 2.2092, -0.3226,  0.6020],
        [-0.0600,  0.9910,  1.3617],
        [-0.3236,  3.1849, -0.4847]])

In [22]:
print(x[:, 1])

tensor([-1.1758,  0.9185, -0.8099,  0.0041,  2.4848])


#### resizing: If you want to resize/reshape tensor, you can use torch.view:

In [23]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)  # the size -1 is inferred from other dimensions
x.size(), y.size(), z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

### NumPy Bridge`

In [24]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [25]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [26]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


#### Converting NumPy Array to Torch Tensor

In [27]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


##### CUDA Tensors

In [28]:
#Tensors can be moved onto any device using the .to method.
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))